Foodee/ember-foxy-forms

addon/components/form-for.js

Allows the promise to be chainable

Return failed promise on FormFor#doSubmit fail

---

addon/templates/components/field-for.hbs
package.json

This was styling zero values as semi-transparent when in fact they are not a placeholder. Fixed.

Fix placeholder for zero values

---

addon/components/field-for.js
addon/components/form-for.js
package.json

* For whatever reason, using Ember.setProperties on a model has unexpected consequences when dealing with dates, seems to mark the same date object as a changedAttribute
* Also, since the purpose of running validations after a field reset was to reset the errors, I've added a `clearValidations`, which clears the validations without having to run them.

Fix issue when using deconst setProps has different outcome on models.

---

tests/dummy/app/templates/docs/usage.md

Just a small typo fix. htm5 -> html5
Cool project! Just reading through the docs now 👍

Fix typo in usage Doc

---

addon/components/field-for.js
addon/services/form-for.js
tests/dummy/app/templates/docs/controls.md
tests/dummy/app/templates/docs/fields.md

This commit adds the ability to pass a name to the @using parameter
which will make the field component lookup your custom component in one
of three places:
1) In your project form-controls/<name>, this is the correct way to
import a custom component
2) In your project form-controls/<name>-control, this method will be
deprecated, but is in place to support the old implementation
3) In foxy-forms form-controls/ff-<name> this is the location of the
default packaged form controls.

Enhance using to allow for custom lookup

---

addon/components/form-controls/ff-checkbox.hbs
addon/components/form-controls/ff-checkbox.js

This commit lets checkboxes be inverted, there are times where you might
want checking a checkbox to have the opposite effect on the underlying
model. Which is to say render selected when its value is absent.

Allow for inversion of checkboxes

---

addon/components/form-controls/ff-checkbox-select.hbs
addon/components/form-controls/ff-checkbox-select.js

This commit allows for the inversion of checkbox selection, useful for
making block lists etc.
It also adds a data test index to the checkbox select.

Allow for inverting checkbox selection

---

addon/components/form-controls/abstract-select.js
addon/components/form-controls/ff-checkbox-select.js
addon/components/form-controls/ff-select.js

* Further reduces responsibility of `coerceValue` method in abstract select to ensure that it's sole responibility is to reduce an object to it's lowest possible form for potential comparisons
* Seperates the responsibility of coercing the value into it's `store` value by providing a `storeValue` method

Ensure abstract select makes proper comparison

---

addon/components/field-for.js

Adds support for overriding the `displayValue` of `field-for` from above.

Add support for `displayValue` override in `field-for`

---

addon/components/field-for.js
addon/components/form-for.hbs
addon/components/form-for.js
addon/services/form-for.js

* Ensures fieldClass get's passed to `field-for` component
* Fixes issue where form controls in the old style couldn't be found because of a syntax error
* Defaults preventsNavigation to false, but allows for a configuration to have it set to true by default

Fix fieldClass passdown and minor fixes

---

addon/components/field-for.js

Fixes an issue where a displayValue might be a number, or an array of strings, but the @arg(prop) decorator throws an error that when validated against the prop definition.

Fix issue that prevents displayValue from being anything but a string

---

addon/components/field-for.js
package.json

* Since .toJSON on Ember Models is deprecated blindly serializing them to check for identity needed to be revised
* Added a check for whether or not an object is a not POJO as a way to optionally map an object to a unique identifier
* All POJOs and primatives will be serialized as before

Prevent .toJSON from being called on ember-models

---

package-lock.json
package.json

Dev dependencies is the wrong area for exposed functionality packages in addons. Moved is-plain-object to main dependencies.

Move is-plain-object into main dependencies

---

package-lock.json
package.json

Ember addons won't auto-import npm packages unless ember-auto-importer is in the main dependencies section.
Tested with yalc instead of yarn/npm link [https://github.com/wclr/yalc](https://github.com/wclr/yalc)

Ensure ember-auto-importer is in not in devDeps but main deps

---

addon/components/field-for.hbs
addon/components/field-for.js
addon/components/form-for.hbs
addon/components/form-for.js
addon/components/label-for.hbs
addon/components/label-for.js
addon/services/form-for.js
config/environment.js
package-lock.json
package.json
tests/dummy/app/templates/docs/usage.md

This commit adds info text to the label component with a default
implementation that uses title.
It also allows you to provide your own label component to render
tooltips as you please.

Add info text

---

addon/components/field-for.hbs
package.json

* Previously, all fields on an inline edit form with callouts would fully render each callout which was a huge performance hit

Ensure lazy instant. of callout for inline fields

---

addon/components/form-controls/abstract-select.js

Allows numbers to be used as a primitive value for abstract select

Allow numbers as values for comparison in select

---

addon/components/field-for.hbs
addon/components/field-for.js
addon/components/form-for.js
addon/services/form-for.js
tests/dummy/app/controllers/docs/usage.js
tests/dummy/app/templates/docs/forms.md
tests/dummy/app/templates/docs/usage.md

This commit adds the ability for a Form to be configured to scroll to
the first error.
It also fixes an issue with the service that would be get stuck in an
infinite loop when aborting a dirty transition.

Add scroll to visible first visible error

---

addon/components/field-for.hbs
addon/components/form-controls/ff-currency.hbs
addon/components/form-controls/ff-input.hbs
addon/components/form-controls/ff-input.js
addon/components/form-controls/ff-multiple-input.hbs
addon/components/form-controls/ff-textarea.hbs

- Now that we removed most of the arguments passed from Form to Field other than `form`, field-for component was updated to use `this.form.something` to access attributes on the form. 
- Those args were updated to use arg types so that when arg is not provided it would default to `this.form.something || someDefaultValue`
- e.g. ` @arg(bool) get readonly() { return this.form?.readonly || false; }`
- However, in the template side, some of the args (`readonly` and `disabled`) were accessed using `@` directly which would result in `undefined` without default value.  And this value is passed to controls.
- On`ff-input-control` component side, it also uses arg type with a default value of true. So because `undefined` is passed due to reasons above, it would default to true which triggered …

Fix ff-input readonly bug

---

addon/components/field-for.js
addon/components/form-for.js

* Allows foxy-forms to reset the model even after the component is destroyed.
* Needed for supporting async willReset on destroy

Allow model to reset after destroy

---

addon/components/field-for.js

This commit returns the ability to override the errors array on a field that was lost when we upgraded.

Add back ability to override errors array

---

addon/components/form-controls/ff-select.js

- Currently ff-select cannot detect boolean values from event.target.value compared with the provided values (when it has boolean as an option) since value from event.target.value is always a string.
- When stringified boolean is found from event object, make it a boolean

Add support for boolean values in select

---

addon/components/form-controls/ff-select.js

Running JSON.parse on strings throws error.
only run it if it is stringified boolean

JSON parse only if value is stringified boolean

---

addon/components/field-for.js
addon/components/form-for.js
tests/integration/components/form-for-test.js

This commit defaults validation options to defined fields to prevent weird errors.

Default validationOptions to defined fields

---

addon/components/field-for.hbs
addon/components/field-for.js

ember attached popover by default has `mouseleave` as an event to hide the callout.
adding an argument so it is configurable and by default do not inlcude mouseleave

add argument for control callout hide/show

---

addon/components/form-for.js
tests/integration/components/form-for-test.js

model-validator does not support validations for fields in arrays .
For example, `{only: ['name', 'email']}` is what it expects.
If it is given an array inside the only array like `{only: ['name',  ['email', 'email-confirmation']]}`, it will skip the validation for the fields in the inner array.
This commit is to make `validationOptions` getter to spread the inner array so that all fields in the array that is provided in `for` to be validated.

support validation for array for infields
